services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    env_file:
      - .env
    networks:
      - laravel_network
    command: >
      sh -c "chown -R www-data:www-data /var/www &&
             chmod -R 755 /var/www/storage &&
             php-fpm"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

# volumes:
#   sqlserver_data: